-- GW2 Trading Assistant — Database Schema

-- Reference data for tracked items
CREATE TABLE IF NOT EXISTS items (
    item_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    rarity TEXT,
    type TEXT,
    level INTEGER DEFAULT 0,
    icon_url TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

-- Historical price snapshots from /v2/commerce/prices (our own collector)
CREATE TABLE IF NOT EXISTS price_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id INTEGER NOT NULL,
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    buy_price INTEGER NOT NULL,
    sell_price INTEGER NOT NULL,
    buy_quantity INTEGER NOT NULL,
    sell_quantity INTEGER NOT NULL,
    FOREIGN KEY (item_id) REFERENCES items(item_id)
);

CREATE INDEX IF NOT EXISTS idx_price_snapshots_item_time
    ON price_snapshots(item_id, timestamp);

-- Daily aggregated price history from DataWars2 API (backfill + enrichment)
CREATE TABLE IF NOT EXISTS price_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id INTEGER NOT NULL,
    date TEXT NOT NULL,
    buy_price_avg INTEGER,
    buy_price_min INTEGER,
    buy_price_max INTEGER,
    buy_price_stdev REAL,
    sell_price_avg INTEGER,
    sell_price_min INTEGER,
    sell_price_max INTEGER,
    sell_price_stdev REAL,
    buy_quantity_avg INTEGER,
    sell_quantity_avg INTEGER,
    buy_sold INTEGER,
    sell_sold INTEGER,
    buy_listed INTEGER,
    sell_listed INTEGER,
    buy_delisted INTEGER,
    sell_delisted INTEGER,
    buy_value INTEGER,
    sell_value INTEGER,
    snapshot_count INTEGER,
    last_accessed TEXT DEFAULT (datetime('now')),
    UNIQUE(item_id, date),
    FOREIGN KEY (item_id) REFERENCES items(item_id)
);

CREATE INDEX IF NOT EXISTS idx_price_history_item_date
    ON price_history(item_id, date);

CREATE INDEX IF NOT EXISTS idx_price_history_last_accessed
    ON price_history(last_accessed);

-- Patch notes from GW2 Wiki (MediaWiki API)
CREATE TABLE IF NOT EXISTS patch_notes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    title TEXT NOT NULL,
    full_text TEXT NOT NULL,
    source_url TEXT,
    affected_systems TEXT,
    fetched_at TEXT DEFAULT (datetime('now')),
    UNIQUE(date, title)
);

-- Reddit posts from r/Guildwars2
CREATE TABLE IF NOT EXISTS reddit_posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    post_id TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    body TEXT,
    upvotes INTEGER DEFAULT 0,
    comment_count INTEGER DEFAULT 0,
    timestamp TEXT NOT NULL,
    url TEXT,
    fetched_at TEXT DEFAULT (datetime('now'))
);

 -- Trading signals generated by the RAG pipeline
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL DEFAULT (datetime('now')),
    item_name TEXT NOT NULL,
    direction TEXT NOT NULL,
    confidence REAL NOT NULL,
    reasoning TEXT,
    time_horizon TEXT,
    expected_move_pct REAL,
    source_documents TEXT,
    trigger_event TEXT,
    status TEXT DEFAULT 'active',
    actual_move_pct REAL,
    validated_at TEXT
 );
